# Generates pretty snake animation, using @Platane's awesome snk action
name: 🐍 Generate Snake Contribution
on:
  workflow_dispatch: # Manual dispatch
  schedule:
    - cron: '30 23 * * *' # Runs at 23:30 every day.
  push:
    paths:
      - .github/workflows/snake-contrib-gif.yml
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
      - name: Generate Snake
        uses: Platane/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "auto update Snake Contribution Animation"